version: 0.1

phases:
  install:
    commands:
      - dotnet restore
  pre_build:
    commands:
      - dotnet lambda package
  build:
    commands:
      - aws cloudformation package --template-file app_def.yml --output-template-file serverless-output.yml --s3-bucket fitness-code-dotnet-input

