version: 0.1

phases:
  install:
    commands:
      - echo Restoring dependant libraries
      - dotnet restore
  pre_build:
    commands:
      - echo Compiling and packaging up code
      - dotnet lambda package
  build:
    commands:
      - echo Setting build number
      - git log --pretty=format:'%h' -n 1
      - BUILD_VERSION=`git log --pretty=format:'%h' -n 1`
      - echo $BUILD_VERSION
      - echo Generating cloudformation template
      - aws cloudformation package --template-file app_def.yml --output-template-file serverless-$BUILD_VERSION.yml --s3-bucket fitness-app-workouts-code

artifacts:
  files:
      - serverless-*.yml 

